name: oxide_ci
on: [push, pull_request]
jobs:
  use-oxide:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - {name: "proj_template_v", command: "cd proj/proj_template_v && make PLATFORM=hps bitstream"}
          - {name: "hps mproj", command: "cd proj/mport && pip3 list && make PLATFORM=hps bitstream software"}
          - {name: "hps_accel test 1", command: "cd proj/hps_accel && make PLATFORM=hps bitstream"}
          - {name: "hps_accel test 2", command: "cd proj/hps_accel && make PLATFORM=hps EXTRA_LITEX_ARGS=\"--cpu-variant=slimopt+cfu\" clean bitstream"}
          - {name: "hps_accel test 3", command: "cd proj/hps_accel && make PLATFORM=hps EXTRA_NEXTPNR_ARGS=\"--placer-heap-timingweight 52\" EXTRA_LITEX_ARGS=\"--separate-arena --cpu-variant=slimopt+cfu --extra-nextpnr-params\" clean bitstream"}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Environment setup
        run: |
          bash scripts/setup -ci
          make env
          source env/conda/bin/activate cfu-common
          source environment
      - name: Tool versions
        run: |
          source env/conda/bin/activate cfu-common
          source environment
          riscv32-elf-newlib-gcc --version
          yosys --version
          nextpnr-nexus --version
      - name: ${{matrix.name}}
        run: |
          source env/conda/bin/activate cfu-common
          source environment
          ulimit -S -t 900
          ulimit -H -t 900
          ${{matrix.command}}
